import os
SECRET_KEY=os.environ['SECRET_KEY']
DB_USERNAME=os.environ['DB_USERNAME']
DB_PASSWORD=os.environ['DB_PASSWORD']
DB_HOST=os.environ['DB_HOST']
DATABASE_NAME=os.environ['DATABASE_NAME']
DB_URI = "mysql+pymysql://%s:%s@%s:3306/%s" % (DB_USERNAME, DB_PASSWORD, DB_HOST, DATABASE_NAME)
SQLALCHEMY_DATABASE_URI = DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS = True
# MYSQL_ROOT_PASSWORD=os.environ['MYSQL_ROOT_PASSWORD']
BLOG_NAME=os.environ['BLOG_NAME']
SECURITY_PASSWORD_SALT=os.environ['SECURITY_PASSWORD_SALT']

# Config for flask_mail
MAIL_SERVER=os.environ['MAIL_SERVER']
MAIL_PORT=os.environ['MAIL_PORT']
MAIL_USERNAME=os.environ['MAIL_USERNAME']
MAIL_PASSWORD=os.environ['MAIL_PASSWORD']
MAIL_USE_TLS = True
MAIL_USE_SSL = False
MAIL_DEFAULT_SENDER=os.environ['MAIL_DEFAULT_SENDER']

# AWS s3 config
BUCKET_NAME=os.environ['BUCKET_NAME']
REGION=os.environ['REGION']

