"""empty message

Revision ID: 49c31e5dc69e
Revises: c0a166695769
Create Date: 2019-04-10 21:49:29.018645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49c31e5dc69e'
down_revision = 'c0a166695769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username', table_name='author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username', 'author', ['username'], unique=True)
    # ### end Alembic commands ###
