"""empty message

Revision ID: 37b71d98ca34
Revises: e3e3108c97c7
Create Date: 2019-04-07 22:25:41.574517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37b71d98ca34'
down_revision = 'e3e3108c97c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_x_post')
    op.drop_index('name', table_name='tag')
    op.drop_table('tag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'tag', ['name'], unique=True)
    op.create_table('tag_x_post',
    sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='tag_x_post_ibfk_1'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='tag_x_post_ibfk_2'),
    sa.PrimaryKeyConstraint('tag_id', 'post_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
