"""empty message

Revision ID: 54a41b8b78a2
Revises: b1717af72fcf
Create Date: 2019-04-07 13:43:36.212531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54a41b8b78a2'
down_revision = 'b1717af72fcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_x_post',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('comment_id', 'post_id')
    )
    op.drop_constraint('post_ibfk_3', 'post', type_='foreignkey')
    op.drop_column('post', 'comment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('comment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('post_ibfk_3', 'post', 'comment', ['comment_id'], ['id'])
    op.drop_table('comment_x_post')
    # ### end Alembic commands ###
