"""empty message

Revision ID: b50347c0ad75
Revises: 3f6ef73497da
Create Date: 2019-04-14 21:14:17.191749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50347c0ad75'
down_revision = '3f6ef73497da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('confirmed', sa.Boolean(), nullable=False))
    op.add_column('author', sa.Column('confirmed_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'confirmed_on')
    op.drop_column('author', 'confirmed')
    # ### end Alembic commands ###
